name: Chisel Book Continous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Verilator
      # should include texlive-full for Latex test
      run: sudo apt-get install verilator
    - name: Setup z3
      run: sudo apt-get install z3
    - name: Run tests
      run: sbt test
    # should run make for the test including Latex
    # - name: Build book
    #   run: |
    #     make gencode
    #     make fig
    #     make book
